services:
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wikicoaster
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3307:3306'

  php:
    image: 'php:8.2-apache'
    volumes:
      - .:/var/www/html
    ports:
      - '8080:80'
    environment:
      DATABASE_URL: "mysql://root:password@database:3306/wikicoaster?serverVersion=8.0"